### ISSUE TITLE
Additional exit condition depending on the output stream

### ISSUE THREAD

**Issue by urbanware-org** [b3-soft-org/amp#1]
When e. g. writing from `/dev/urandom` onto a disk device such as `/dev/sdb`, `amp` does not abort when there is no space left on the device.

The exit condition is the end of the input stream, which most likely never happens when using `/dev/urandom`.

**Comment by b3-soft-org** [comment]
Thank you for your feedback!

I haven't seen this coming. `amp` was intended to read from a finite stream and write to multiple (finite) streams. But what you described makes absolute sense. I hope my - yet untested - fix solves this issue.

I will test the changes in the next few days. I am also excited to hear what you think and if it works for you...

**Comment by urbanware-org** [comment]
> Thank you for your feedback!

Thank you for your fast response!

> I hope my - yet untested - fix solves this issue

Looks good so far!

I just wrote from `/dev/urandom` onto `/dev/sda` and `/dev/sdb` simultaneously (both devices are identical hard disk drives with the size of 500 GB). Both of them contained a partition table with various partitions before.

After about 1.5 hours `amp` exited with code `0` and the partition tables on both devices have been destroyed as expected.

However, as already mentioned, both devices are identical hardware with the same size, so I could not test what happens when the devices have a different size and one of them runs full.

**Comment by b3-soft-org** [comment]
I'm glad to hear that the changes worked for you!

Right now, I'm working on some minor changes (like including log messages) and a few test cases, like the one you mentioned.

Speaking of your scenario: If you write random bytes (from an infinite input stream like `/dev/urandom`) to hard drives or partitions of different sizes, `amp` should still work as expected and simply ignore the stream (or hard drive or partition) that ran full. First, the bytes written to every output stream are compared to the bytes read from the input stream and if there's an imbalance, the stream is marked as 'broken' and will then be ignored. And second, there is a test for EOF for every output stream and in case this test becomes true, the stream is then ignored too. Please let me know, if you encounter a different behavior.

I hope you really intended to overwrite both hard drives with random data. If not, please don't blame `amp` if you irrevocably deleted all your precious data ;-)

And thank you again for your feedback!

**Comment by urbanware-org** [comment]
> I hope you really intended to overwrite both hard drives with random data

Yes, of course! :smile:
Furthermore, I have a nice backup of `/dev/urandom` now.

> different sizes, `amp` should still work as expected and simply ignore

Due to the fact, that the hard disks I used are the same size (as already mentioned) I decided to try what happens using USB 2.0 flash drives (for testing purposes, only) with different sizes, one with 16 GB and another with 32 GB.

I'm aware of the fact, that erasing flash drives using this method may not be the best way, but this was just experimental to check what happens with devices with a different size.

Running `amp` took more than an hour and after some time I noticed that none of the status LEDs on the devices were flashing anymore like they were idle. After canceling by hitting **Ctrl**+**C**, `amp` instantly exited with return code `130`.

However, when I start `amp` again and try to cancel the process after e. g. one minute, `amp` takes some time to exit (until then the status LEDs are flashing once in a while), also with code `130`.

Correct me if I'm wrong, it seems that `amp` did not exit when after it had overwritten the USB flash drives.

**Comment by b3-soft-org** [comment]
Hey!

Sorry for my late reply! I've been quite busy evaluating the new issue and was working hard to improve `amp` with some awesome new features. Although this is just a very early alpha version and the code looks awful, at least it should run.

I'm really excited to hear what you think and if it works for you. Please let me know!

I will try to clean up the code in the next few days and upload another version.

Thank you for testing and bug reporting!

**Comment by urbanware-org** [comment]
You're welcome! I'm glad I can help with my tests.

> Sorry for my late reply! I've been quite busy evaluating the new issue and was working hard to improve `amp` with some awesome new features

Not a problem at all. I noticed that the project has changed significantly.

> I'm really excited to hear what you think and if it works for you

I'm impressed by the new version and its new great features. Just tried it out and it works as a charm!

Great work and thanks again!

**Comment by b3-soft-org** [comment]
Thanks for your reply!

Glad to hear, this one works for you. I also fixed some bugs I've found myself. So if you like, you can download and compile the most recent version.

Event though the version you've tested isn't completely done yet, can you verify that the original bug you addressed with this issue is fixed? If so, please be so kind and close this issue. And if you find any other bugs, please let me know and open another issue...

**Comment by b3-soft-org** [comment]
Damn it... Clicked the wrong button again and accidentally closed the issue

**Comment by urbanware-org** [comment]
> So if you like, you can download and compile the most recent version

Just tried it out (with two devices with a different size) and it works as expected. Great work.

> can you verify that the original bug you addressed with this issue is fixed? If so, please be so kind and close this issue

Yes, the issue is fixed. Due to this, I'm closing this ticket as requested.

Thanks again!
